version: "3.7"
services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - ./app:/app
  db:
    image: mysql:5.7
    ports:
      - "5001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sherlockeD123
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  ui:
    build: ./react-ctrlf
    ports:
      - "5002:3000"
    volumes:
      - ./react-ctrlf:/usr/src/app
    entrypoint: ["npm", "start"]
